name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REGISTRY_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${DOCKER_IMAGE_NAME} \
            --image ${GCP_REGISTRY_NAME}/${GCP_PROJECT_ID}/${DOCKER_IMAGE_NAME}:${GITHUB_SHA} \
            --platform managed \
            --region ${GCP_REGION} \
            --allow-unauthenticated

    #   - name: Build Docker image
    #     run: |
    #       docker build -t gcr.io/my-awesome-project-12345/gcloud-run-app .

    #   - name: Push Docker image to Google Container Registry
    #     run: |
    #       docker push gcr.io/my-awesome-project-12345/gcloud-run-app

    #   - name: Deploy to Google Cloud Run
    #     run: |
    #       gcloud run deploy gcloud-run-app \
    #         --image gcr.io/my-awesome-project-12345/gcloud-run-app \
    #         --platform managed \
    #         --region YOUR_REGION \
    #         --allow-unauthenticated
