name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          #   workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          #   service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    #   - name: Set up Google Cloud SDK
    #     uses: google-github-actions/setup-gcloud@v2
    #     with:
    #       project_id: ${{ secrets.GCP_PROJECT_ID }}

    #   - name: Build Docker image
    #     run: |
    #       docker build -t gcr.io/my-awesome-project-12345/gcloud-run-app .

    #   - name: Push Docker image to Google Container Registry
    #     run: |
    #       docker push gcr.io/my-awesome-project-12345/gcloud-run-app

    #   - name: Deploy to Google Cloud Run
    #     run: |
    #       gcloud run deploy gcloud-run-app \
    #         --image gcr.io/my-awesome-project-12345/gcloud-run-app \
    #         --platform managed \
    #         --region YOUR_REGION \
    #         --allow-unauthenticated
